// generated by go run gen.go; DO NOT EDIT

package icons

var list = []struct {
	name string
	data []byte
}{
	{"ToggleCheckBox", ToggleCheckBox},
	{"ToggleCheckBoxOutlineBlank", ToggleCheckBoxOutlineBlank},
	{"ToggleIndeterminateCheckBox", ToggleIndeterminateCheckBox},
	{"ToggleRadioButtonChecked", ToggleRadioButtonChecked},
	{"ToggleRadioButtonUnchecked", ToggleRadioButtonUnchecked},
	{"ToggleStar", ToggleStar},
	{"ToggleStarBorder", ToggleStarBorder},
	{"ToggleStarHalf", ToggleStarHalf},
}
